name: .NET

on:
  pull_request_target:
    types:
      - closed
    paths:
      - 'ConsoleApp1/**'

env:
  ConsoleProjectPath: ${{github.workspace}}/ConsoleApp1
  NugetDirectory: ${{github.workspace}}/nuget

jobs:
  publish_nuget_package_if_pr_is_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Pack ConsoleProject
      run: dotnet pack ${{env.ConsoleProjectPath}} --configuration Release --output ${{env.NugetDirectory}}

    - name: Publish to GitHub NuGet Registry
      run: |
          foreach file in ${{env.NuGetDirectory}}/*.nupkg; do
            dotnet nuget push $file "${{ secrets.GITHUB_TOKEN }}" --source "github" --skip
          done
